#!/bin/bash

CF=config
CFG=config_g
CFS=config_s
OK="OK"
GIT=".git/"
FIRST="school git"
SECOND="remote git"
COMMENT="progress"

git status
git add *
if [ "$#" -gt 0 ]
then
	git commit -m "$1"
else
	git commit -m "${COMMENT}"
fi
echo "----------------------------------------------------------------"
echo "push to ${FIRST} git"
git push
if [ -a $GIT$CF ]
	then
		mv $GIT/$CF $GIT/$CFS
	else
		echo "${CF} file not found"
		exit 1
fi
if [ -a $GIT$CFG ]
	then
		mv $GIT/$CFG $GIT/$CF
	else
		echo "${CFG} file not found"
		exit 1
fi
echo "----------------------------------------------------------------${OK} (${FIRST} git)"
echo "push to ${SECOND} git"
git push
mv $GIT/$CF $GIT/$CFG
mv $GIT/$CFS $GIT/$CF
echo "----------------------------------------------------------------${OK} (${SECOND} git)"
